-- db exploration
-- explore all objects in the db
select * from information_schema.TABLES;

-- explore all columns in the db
select * from INFORMATION_SCHEMA.COLUMNS;

-- columns from specific table
select * from INFORMATION_SCHEMA.COLUMNS where table_name like 'dim%' or table_name like 'fact%';

-- dimension exploration
-- identifying the unique values in each dimension

--- ex.: explore all countries our customers come from
select distinct country from gold.dim_customers;

-- ex.: explore all categories "the major divisions"
select distinct category, subcategory, product_name from gold.dim_products;

-- date exploration
-- identify the earliest and latest dates
-- understand the scope of data and timespan

--ex.: find the first and last order date
-- how many years of sales
select min(order_date) as first_order_date, max(order_date) as last_order_date,
datediff(year, min(order_date), max(order_date)) as years_sales from gold.fact_sales;

-- wx.: select the oldest and youngest customer
select min(birthdate) as oldest_customer, DATEDIFF(year, min(birthdate), getdate()) as oldest_age,
max(birthdate) as youngest_customer, DATEDIFF(year, max(birthdate), getdate()) as youngest_age
from gold.dim_customers;

-- measures exploration
-- calculate the key metrice of the business

-- ex.: find the total sales
select sum(sales_amount) as total_sales from gold.fact_sales;

-- ex.: find how many items are sold
select sum(quantity) as total_quantity from gold.fact_sales;

-- ex.: find the avg selling price
select avg(price) as average_price from gold.fact_sales;

-- ex.: find the total number of orders
select count(order_number) as total_number_orders from gold.fact_sales;
select count(distinct order_number) as total_number_orders from gold.fact_sales;
select * from gold.fact_sales ;

-- ex.: find the total number of products
select count(product_key) as total_number_products from gold.dim_products;

-- ex.: find the total number of customers
select count(customer_key) as total_number_customers from gold.dim_customers;

-- ex.: find the total number of customers that has placed an order
select count(distinct customer_key) as total_number_customers from gold.fact_sales;

-- generate a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total Quantity', sum(quantity) from gold.fact_sales union all
select 'Average Price', avg(price) from gold.fact_sales union all
select 'Total Orders', count(distinct order_number) from gold.fact_sales union all
select 'Total Products', count(product_key) from gold.dim_products union all
select 'Total Customers', count(customer_key) from gold.dim_customers union all
select 'Total Customers that Ordered', count(distinct customer_key) from gold.fact_sales;

-- magnitude analysis
-- compare the measure values across different categories and values

-- ex.: find total customers by countries
select country, count(customer_key) as [Total Customers] from gold.dim_customers 
group by country order by [Total Customers] desc;

-- ex.: find total customers by gender
select gender, count(customer_key) as [Total Customers] from gold.dim_customers 
group by gender order by [Total Customers] desc;

-- ex.: find total products by category
select category, count(product_key) as [Total Products] from gold.dim_products 
group by category order by [Total Products] desc;

-- ex.: average costs in each category
select category, avg(CAST(product_cost AS DECIMAL(18,2))) as [Average Cost] from gold.dim_products 
group by category order by [Average Cost] desc;

-- ex.: total revenue generated for each category
-- comeca com fact table e faz left join com o dimension
select p.category, sum(s.sales_amount) as [Total Revenue]
from gold.fact_sales as s left join gold.dim_products as p on s.product_key = p.product_key
group by p.category order by [Total Revenue] desc;

-- ex.: total revenue generated by each customer
select c.customer_key, c.first_name, c.last_name, sum(s.sales_amount) as [Total Revenue]
from gold.fact_sales as s left join gold.dim_customers as c on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name order by [Total Revenue] desc;

-- ex.: whats the distribution of sold items across countries
select c.country, sum(s.quantity) as [Items Sold]
from gold.fact_sales as s left join gold.dim_customers as c on s.customer_key = c.customer_key
group by c.country order by [Items Sold] desc;

-- ranking
-- order the value of dimensions by measure. top n performers/bottom n performers

-- ex.: which 5 products generate the highest revenue?
select top 5 p.product_name, sum(s.sales_amount) as [Total Revenue]
from gold.fact_sales as s left join gold.dim_products as p on s.product_key = p.product_key
group by p.product_name order by [Total Revenue] desc;

-- ex.: 5 worst performing products in terms of sales
select top 5 p.product_name, sum(s.sales_amount) as [Total Revenue]
from gold.fact_sales as s left join gold.dim_products as p on s.product_key = p.product_key
group by p.product_name order by [Total Revenue];

-- window functions are for more flexible and complex queries with extra details

-- ex.: top 10 customers who generated the highest revenue
select top 10 c.customer_key, c.first_name, c.last_name, sum(s.sales_amount) as [Total Revenue]
from gold.fact_sales as s left join gold.dim_customers as c on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name order by [Total Revenue] desc;

-- ex.: find the 3 customers with the fewest orders placed
select top 3 c.customer_key, c.first_name, c.last_name, count(distinct s.order_number) as [Total Orders]
from gold.fact_sales as s left join gold.dim_customers as c on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name order by [Total Orders];